package com.blagij;

public enum State {
    INITIAL,
    SINGLE_SLASH,
    SINGLE_LINE_COMMENT,
    MULTI_LINE_COMMENT,
    STAR_IN_MULTI_LINE_COMMENT,
    STRING_LITERAL,
    STRING_LITERAL_SLASH,
    CHAR_LITERAL,
    CHAR_LITERAL_SLASH,
    SINGLE_EQUAL,
    SINGLE_MINUS,
    SINGLE_PLUS,
}
